name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Tạo file .env từ secret
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ vars.HARBOR_NAMESPACE }}/${{ vars.HARBOR_IMAGE }}:latest
          ${{ vars.HARBOR_NAMESPACE }}/${{ vars.HARBOR_IMAGE }}:${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max